#ifndef BLACKBOARDHPP
#define BLACKBOARDHPP
#include <osg/AlphaFunc_pmoc.hpp>
#include <osg/AnimationPath_pmoc.hpp>
#include <osg/ApplicationUsage_pmoc.hpp>
#include <osg/ArgumentParser_pmoc.hpp>
#include <osg/Array_pmoc.hpp>
#include <osg/ArrayDispatchers_pmoc.hpp>
#include <osg/AudioStream_pmoc.hpp>
#include <osg/AutoTransform_pmoc.hpp>
#include <osg/Billboard_pmoc.hpp>
#include <osg/BlendColor_pmoc.hpp>
#include <osg/BlendEquation_pmoc.hpp>
#include <osg/BlendFunc_pmoc.hpp>
#include <osg/BoundingBox_pmoc.hpp>
#include <osg/BoundingSphere_pmoc.hpp>
#include <osg/BoundsChecking_pmoc.hpp>
#include <osg/BufferIndexBinding_pmoc.hpp>
#include <osg/Camera_pmoc.hpp>
#include <osg/CameraView_pmoc.hpp>
#include <osg/ClampColor_pmoc.hpp>
#include <osg/ClearNode_pmoc.hpp>
#include <osg/ClipNode_pmoc.hpp>
#include <osg/ClipPlane_pmoc.hpp>
#include <osg/ClusterCullingCallback_pmoc.hpp>
#include <osg/CollectOccludersVisitor_pmoc.hpp>
#include <osg/ColorMask_pmoc.hpp>
#include <osg/ColorMatrix_pmoc.hpp>
#include <osg/ComputeBoundsVisitor_pmoc.hpp>
#include <osg/Config_pmoc.hpp>
#include <osg/ConvexPlanarOccluder_pmoc.hpp>
#include <osg/ConvexPlanarPolygon_pmoc.hpp>
#include <osg/CoordinateSystemNode_pmoc.hpp>
#include <osg/CopyOp_pmoc.hpp>
#include <osg/CullFace_pmoc.hpp>
#include <osg/CullSettings_pmoc.hpp>
#include <osg/CullStack_pmoc.hpp>
#include <osg/CullingSet_pmoc.hpp>
#include <osg/DeleteHandler_pmoc.hpp>
#include <osg/Depth_pmoc.hpp>
#include <osg/DisplaySettings_pmoc.hpp>
#include <osg/DrawPixels_pmoc.hpp>
#include <osg/Endian_pmoc.hpp>
#include <osg/Export_pmoc.hpp>
#include <osg/Fog_pmoc.hpp>
#include <osg/FragmentProgram_pmoc.hpp>
#include <osg/FrameBufferObject_pmoc.hpp>
#include <osg/FrameStamp_pmoc.hpp>
#include <osg/FrontFace_pmoc.hpp>
#include <osg/GL_pmoc.hpp>
#include <osg/GL2Extensions_pmoc.hpp>
#include <osg/GLBeginEndAdapter_pmoc.hpp>
#include <osg/GLExtensions_pmoc.hpp>
#include <osg/GLObjects_pmoc.hpp>
#include <osg/GLU_pmoc.hpp>
#include <osg/Geode_pmoc.hpp>
#include <osg/Geometry_pmoc.hpp>
#include <osg/GraphicsContext_pmoc.hpp>
#include <osg/GraphicsCostEstimator_pmoc.hpp>
#include <osg/GraphicsThread_pmoc.hpp>
#include <osg/Group_pmoc.hpp>
#include <osg/Hint_pmoc.hpp>
#include <osg/Image_pmoc.hpp>
#include <osg/ImageSequence_pmoc.hpp>
#include <osg/ImageStream_pmoc.hpp>
#include <osg/ImageUtils_pmoc.hpp>
#include <osg/KdTree_pmoc.hpp>
#include <osg/LOD_pmoc.hpp>
#include <osg/Light_pmoc.hpp>
#include <osg/LightModel_pmoc.hpp>
#include <osg/LightSource_pmoc.hpp>
#include <osg/LineSegment_pmoc.hpp>
#include <osg/LineStipple_pmoc.hpp>
#include <osg/LineWidth_pmoc.hpp>
#include <osg/LogicOp_pmoc.hpp>
#include <osg/Material_pmoc.hpp>
#include <osg/Math_pmoc.hpp>
#include <osg/Matrix_pmoc.hpp>
#include <osg/MatrixTransform_pmoc.hpp>
#include <osg/Matrixd_pmoc.hpp>
#include <osg/Matrixf_pmoc.hpp>
#include <osg/MixinVector_pmoc.hpp>
#include <osg/Multisample_pmoc.hpp>
#include <osg/Node_pmoc.hpp>
#include <osg/NodeCallback_pmoc.hpp>
#include <osg/NodeTrackerCallback_pmoc.hpp>
#include <osg/NodeVisitor_pmoc.hpp>
#include <osg/Notify_pmoc.hpp>
#include <osg/Object_pmoc.hpp>
#include <osg/Observer_pmoc.hpp>
#include <osg/ObserverNodePath_pmoc.hpp>
#include <osg/OccluderNode_pmoc.hpp>
#include <osg/OcclusionQueryNode_pmoc.hpp>
#include <osg/OperationThread_pmoc.hpp>
#include <osg/PagedLOD_pmoc.hpp>
#include <osg/PatchParameter_pmoc.hpp>
#include <osg/Plane_pmoc.hpp>
#include <osg/Point_pmoc.hpp>
#include <osg/PointSprite_pmoc.hpp>
#include <osg/PolygonMode_pmoc.hpp>
#include <osg/PolygonOffset_pmoc.hpp>
#include <osg/PolygonStipple_pmoc.hpp>
#include <osg/Polytope_pmoc.hpp>
#include <osg/PositionAttitudeTransform_pmoc.hpp>
#include <osg/PrimitiveRestartIndex_pmoc.hpp>
#include <osg/PrimitiveSet_pmoc.hpp>
#include <osg/Program_pmoc.hpp>
#include <osg/Projection_pmoc.hpp>
#include <osg/ProxyNode_pmoc.hpp>
#include <osg/Quat_pmoc.hpp>

#include <osg/Drawable_pmoc.hpp>
#include <osg/RenderInfo_pmoc.hpp>
#include <osg/SampleMaski_pmoc.hpp>
#include <osg/Scissor_pmoc.hpp>
#include <osg/ScriptEngine_pmoc.hpp>
#include <osg/Sequence_pmoc.hpp>
#include <osg/ShadeModel_pmoc.hpp>
#include <osg/Shader_pmoc.hpp>
#include <osg/ShaderAttribute_pmoc.hpp>
#include <osg/ShaderComposer_pmoc.hpp>
#include <osg/ShadowVolumeOccluder_pmoc.hpp>
#include <osg/Shape_pmoc.hpp>
#include <osg/ShapeDrawable_pmoc.hpp>
#include <osg/State_pmoc.hpp>
#include <osg/StateAttribute_pmoc.hpp>
#include <osg/StateAttributeCallback_pmoc.hpp>
#include <osg/StateSet_pmoc.hpp>
#include <osg/Stats_pmoc.hpp>
#include <osg/Stencil_pmoc.hpp>
#include <osg/StencilTwoSided_pmoc.hpp>
#include <osg/Switch_pmoc.hpp>
#include <osg/TemplatePrimitiveFunctor_pmoc.hpp>
#include <osg/TexEnv_pmoc.hpp>
#include <osg/TexEnvCombine_pmoc.hpp>
#include <osg/TexEnvFilter_pmoc.hpp>
#include <osg/TexGen_pmoc.hpp>
#include <osg/TexGenNode_pmoc.hpp>
#include <osg/TexMat_pmoc.hpp>
#include <osg/Texture_pmoc.hpp>
#include <osg/Texture1D_pmoc.hpp>
#include <osg/Texture2D_pmoc.hpp>
#include <osg/Texture2DArray_pmoc.hpp>
#include <osg/Texture2DMultisample_pmoc.hpp>
#include <osg/Texture3D_pmoc.hpp>
#include <osg/TextureBuffer_pmoc.hpp>
#include <osg/TextureCubeMap_pmoc.hpp>
#include <osg/TextureRectangle_pmoc.hpp>
#include <osg/Timer_pmoc.hpp>
#include <osg/TransferFunction_pmoc.hpp>
#include <osg/Transform_pmoc.hpp>
#include <osg/TriangleFunctor_pmoc.hpp>
#include <osg/TriangleIndexFunctor_pmoc.hpp>
#include <osg/Uniform_pmoc.hpp>
#include <osg/UserDataContainer_pmoc.hpp>
#include <osg/ValueObject_pmoc.hpp>
#include <osg/Vec2_pmoc.hpp>
#include <osg/Vec2b_pmoc.hpp>
#include <osg/Vec2d_pmoc.hpp>
#include <osg/Vec2f_pmoc.hpp>
#include <osg/Vec2i_pmoc.hpp>
#include <osg/Vec2s_pmoc.hpp>
#include <osg/Vec2ub_pmoc.hpp>
#include <osg/Vec2ui_pmoc.hpp>
#include <osg/Vec2us_pmoc.hpp>
#include <osg/Vec3_pmoc.hpp>
#include <osg/Vec3b_pmoc.hpp>
#include <osg/Vec3d_pmoc.hpp>
#include <osg/Vec3f_pmoc.hpp>
#include <osg/Vec3i_pmoc.hpp>
#include <osg/Vec3s_pmoc.hpp>
#include <osg/Vec3ub_pmoc.hpp>
#include <osg/Vec3ui_pmoc.hpp>
#include <osg/Vec3us_pmoc.hpp>
#include <osg/Vec4_pmoc.hpp>
#include <osg/Vec4d_pmoc.hpp>
#include <osg/Vec4f_pmoc.hpp>
#include <osg/Vec4i_pmoc.hpp>
#include <osg/Vec4s_pmoc.hpp>
#include <osg/Vec4ub_pmoc.hpp>
#include <osg/Vec4ui_pmoc.hpp>
#include <osg/Vec4us_pmoc.hpp>
#include <osg/Version_pmoc.hpp>
#include <osg/VertexProgram_pmoc.hpp>
#include <osg/View_pmoc.hpp>
#include <osg/Viewport_pmoc.hpp>
#include <osg/buffered_value_pmoc.hpp>
#include <osg/fast_back_stack_pmoc.hpp>
#include <osg/io_utils_pmoc.hpp>
#include <osg/observer_ptr_pmoc.hpp>

#include <osg/BufferObject_pmoc.hpp>
#include <osg/ref_ptr_pmoc.hpp>

#include <osg/Referenced_pmoc.hpp>
#endif
